### PR TITLE
Webtorrent support

### PR DESCRIPTION
**Pull request by anacrolix**
Support webtorrent per https://github.com/anacrolix/torrent/issues/138.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#138: Webtorrent support](https://issuehunt.io/repos/28986292/issues/138)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by backkem** [comment]
I was trying to setup a local swarm using [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker). Am I correct in assuming that `cmd/torrent` doesn't have a seeding side yet?

**Comment by anacrolix** [comment]
I think you mean to pass `-seed` to ensure `cmd/torrent` seeds altruistically, and after completing the downloads.

**Comment by Sean-Der** [comment]
🔥 This is so exciting! I am going to get some numbers, but this should be SO much better then using electron

**Comment by anacrolix** [comment]
There's some more improvements to be made, but the hard work is done.

**Pull request merged**
