### PR TITLE
Use gobwas/ws instead of gorilla/webtorrent

### PR DESCRIPTION
**Pull request by gitpubber**
Closes https://github.com/anacrolix/torrent/issues/500

This successfully compiles and is tried on my computer.

With this patch, better gobwas/ws will be used instead of gorilla/webtorrent

### CODE REVIEW

**Comment by anacrolix** [comment]
I think the *net.Conn should be just net.Conn, otherwise looks good.

**Comment by gitpubber** [comment]
> I think the *net.Conn should be just net.Conn, otherwise looks good.

You have checked whether *websocket.Conn is nil .What should be the logic there?

**Comment by gitpubber** [comment]
@anacrolix can you please tell what should be done here?

https://github.com/anacrolix/torrent/blob/3e248a7fcad4662eda79e8dfbfbdfd6f30f6e90e/webtorrent/tracker_client.go#L238

**Comment by anacrolix** [comment]
You can still compare net.Conn with nil. It will work fine.

**Comment by anacrolix** [comment]
In the future you can just push more commits to the PR, or change your commits and force push. No need to open another PR.

**Pull request closed without merging**
