### PR TITLE
Correct `connIsIpv6`

### PR DESCRIPTION
**Pull request by YenForYang**
Not sure if the current implementation works, or if it does what it's intended to do. Looks like it checks if an address is IPv6 -- if this is the case, then there is a less roundabout way of doing so.

### CODE REVIEW

**Comment by anacrolix** [comment]
I've had issues with net.Addr.String allocating too much in the past. I'm worried about changing this.

**Comment by tsynik** [comment]
return rip.To4() == nil && rip.To16() != nil works as expected.

**Comment by YenForYang** [comment]
Hmm then I'll change it to not use `String` if the current implementation works as expected. Namely the `To4()` and `To16()` calls can be squashed into something less confusing, but slightly more verbose.

**Comment by YenForYang** [comment]
@anacrolix `addrIpOrNil` was used in the original implementation and also calls `String()` if `net.Addr` is not `UDPAddr` or `TCPAddr`. I think I'll fallback to a string check just like `addrIpOrNil`.

**Comment by tsynik** [comment]
this eliminates use of net.Addr.String but doesn't it better use  addrIsIpv6 for new func?

**Comment by anacrolix** [comment]
It's an interesting idea, and I like your intrusive ipv4 in ipv6 test, but I'm loathe to change this without more tests and benchmarks. Especially regarding the connLessTrusted call, which I think is called in to from somewhere performance critical at the moment.

**Comment by anacrolix** [comment]
If I change this I'll probably use `net/netip`, and propagate the family around with the connection.

**Pull request closed without merging**
