### PR TITLE
Fix info_hash url encoding

### PR DESCRIPTION
**Pull request by YenForYang**

### CODE REVIEW

**Comment by YenForYang** [comment]
Ah after some testing it looks like even `PathEscape` sometimes uses `+` instead of `%20`. I think resorting to `strings.Replace()` may be the only way

**Comment by anacrolix** [comment]
I'm confused, doesn't QueryEscape already encode spaces to `%20`? You're welcome to add the logging change if it helps.

**Comment by anacrolix** [comment]
@YenForYang any update on this?

**Comment by YenForYang** [comment]
Doesn't look like QueryEscape uses %20 consistently. I've been doing an explicit strings.Replace and it works great.

**Comment by YenForYang** [comment]
I'll submit my current changes, but I doubt you'll like the looks of it. I basically ditched using `url.Values` and decided to build the string from scratch. I actually find it more readable and it hides less "magic" IMO. I think finer control over building the query is ultimately needed; the url package simply doesn't provide this.

**Comment by YenForYang** [comment]
Just a side note -- We probably won't get more control of the percent encoding with QueryEscape, given this issue: https://github.com/golang/go/issues/13982

**Comment by anacrolix** [comment]
@YenForYang what about https://github.com/anacrolix/torrent/pull/591 instead?

**Pull request closed without merging**
