### PR TITLE
Added Methods to Update Rate Limiters and Change IPBlocklist

### PR DESCRIPTION
**Pull request by gitpubber**
@anacrolix , This is necessary to change those values without restarting Torrent Client

### CODE REVIEW

**Comment by anacrolix** [comment]
It's a fair PR, but I'm certain that iplist.Ranger and *rate.Limiter can be altered out of band with the Client. It doesn't need to be aware, as long as synchronization is present on the implementations chosen. I'm sure that *rate.Limiter does, see https://pkg.go.dev/golang.org/x/time/rate. A thread-safe version of iplist.Ranger will fix the other issue.

I really don't want to grow the API more than it needs to, it already has a lot of legacy cruft.

**Comment by gitpubber** [comment]
@anacrolix ,i will directly manipulate *rate.Limiter then. what can be done about iplist.Ranger if i need to change it(i just wanted to update blocklist once per day)

**Comment by anacrolix** [comment]
@gitpubber which iplist.Ranger implementation are you using? You could make a PR to add locking to the implementation, and some methods to allow updating the list underneath. I will evaluate how difficult it is based on which implementation being used, and possibly accept the method to change the IP blocklist in this PR if it looks too difficult or not possible.

**Comment by gitpubber** [comment]
@anacrolix , i am using github.com/anacrolix/torrent/iplist itself.


```
func FetchBlockList() (*iplist.IPList, error) {
	resp, err := http.Get(BlockListURL)
	if err != nil {
		return nil, err
	}

	// Limit Response
	blocklistReader := io.LimitReader(resp.Body, 20971520)

	// Extract file
	gzipReader, err := gzip.NewReader(blocklistReader)

	if err != nil {
		log.Printf("Error extracting blocklist: %s", err)
		return nil, err
	}

	// Read blocklist
	blocklist, err := iplist.NewFromReader(gzipReader)
	if err != nil {
	        log.Println("Error reading blocklist: ", err)
		return nil, err
	}
	_ = resp.Body.Close()
	log.Println("Loading blocklist of ", blocklist.NumRanges(), " Ranges")
	return blocklist, nil
}
```

**Comment by gitpubber** [comment]
and i would like to update this blocklist once per day. what do you suggest @anacrolix  ?

**Comment by anacrolix** [comment]
Nice. I'd create something like
```
type SynchronizedRanger struct {
    mu sync.RWMutex
    inner iplist.Ranger
}
```
With Lookup and NumRanges that make use of the inner Ranger, using a read lock. Then in your daily blocklist fetch, I'd build a new Ranger, lock the SynchronizedRanger and replace the inner.

**Comment by gitpubber** [comment]
Thank you @anacrolix , i will do as you said

**Pull request closed without merging**
