### PR TITLE
Use gobwas/ws instead of gorilla/websocket

### PR DESCRIPTION
**Pull request by gitpubber**
Fixes  https://github.com/anacrolix/torrent/pull/504

Everything is properly done ,this time @anacrolix

### CODE REVIEW

**Comment by anacrolix** [comment]
Looks good, I'll just do some testing when I get time.

**Comment by gitpubber** [comment]
> Looks good, I'll just do some testing when I get time.

Please try to do this atleast within this week . Thank you

**Comment by gitpubber** [comment]
Any update on this, @anacrolix ?

**Comment by gitpubber** [comment]
What's update on this @anacrolix ?

**Comment by gitpubber** [comment]
Hello, @anacrolix , any updates on this?

**Comment by gitpubber** [comment]
Any update on this, @anacrolix

**Comment by gitpubber** [comment]
@anacrolix how can I test webtorrent peers?

**Comment by gitpubber** [comment]
@anacrolix did you test?

**Comment by anacrolix** [comment]
I tested. It's not connecting to webtorrent peers for some reason. I didn't look in to it more, you're welcome to have a look. I tested with sintel.torrent, and `cmd/torrent download -tcppeers=false -utppeers=false --disablewebseeds`.

**Comment by gitpubber** [comment]
@anacrolix why did you disable webseed? isn't websocket required for webseed?

btw,i will take the look at it again

**Comment by gitpubber** [comment]
@anacrolix i was wrong. gorilla/websocket seems mature at this stage.

this commit of mine seems to close connection on response code.

so,better use gorilla/websocket only

**Pull request closed without merging**
