### PR TITLE
acceptLimitClearer: Avoiding reallocating timer in loop

### PR DESCRIPTION
**Pull request by YenForYang**

### CODE REVIEW

**Comment by YenForYang** [comment]
Whoops forgot to `Stop()` the timer. I think you can squash the commits

**Comment by anacrolix** [comment]
I think this neglects to Reset the timer or use a ticker.

**Comment by YenForYang** [comment]
Yup you're right; I forgot to account for the `lock()` delay.

**Comment by anacrolix** [comment]
Is it really worth the extra 3 lines for something that allocates once every 15 mins? We'd be better off having the entire goroutine run from a timer, so it's not sitting in the scheduler: except that it's a good way to know if the routine has leaked 🤔 .

**Comment by YenForYang** [comment]
Yep definitely not worth it lol. I missed the simpler, better solution -- using a Ticker. This should be better than using `timer.After`.

**Comment by anacrolix** [comment]
I think I prefer to keep this the way it was. Thanks for experimenting with it.

**Pull request closed without merging**
