### PR TITLE
go.mod seems was updated to go21 by accident

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by anacrolix** [comment]
Something upstream forces it to go1.21 and I can't figure out why 😢 .

**Comment by AskAlexSharov** [comment]
I think update of squirrel helped: https://github.com/anacrolix/torrent/pull/868/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R20 - no build error on CI: https://github.com/anacrolix/torrent/actions/runs/6169271367/job/16743198490?pr=868#step:4:8

**Comment by anacrolix** [comment]
I fixed this upstream, should be fixed in https://github.com/anacrolix/torrent/commit/29bea6d844892ab3ea0b99c5204facb97b1953e4.

**Comment by anacrolix** [comment]
A subsequent commit also fixes the 1.19 issues.

**Pull request closed without merging**
