### PR TITLE
Trim allocations when returning FilePieceState

### PR DESCRIPTION
**Pull request by YenForYang**
Use of `append` in `File.State()` can be eliminated in favor of precalculating piece count, calling `make()` and assigning directly. Removes the need of keeping track of remaining bytes and making additional checks when looping over pieces.

### CODE REVIEW

**Comment by anacrolix** [comment]
It's a very explicit way to do it. The lazy version might be allocate with the cap set, make(a, b, cap). Have you had performance overhead here?

**Comment by anacrolix** [comment]
@YenForYang I've noticed the theme with preallocating instead of creating slices with sufficient capacity and appending. I'm very happy to accept these changes if you can just link me to something showing it's faster. Cheers

**Comment by YenForYang** [comment]
Made another change -- should be inlineable now (assuming its cost isn't too high). Seems like all my requests are on inlining lol.

**Comment by anacrolix** [comment]
My eyes are glazing over checking this. Unless there's a performance issue in this function, it's hard to see that it's worth changing.

**Pull request closed without merging**
