### PR TITLE
make completion configurable

### PR DESCRIPTION
**Pull request by mlmhl**
In my environment, store the pieces completion information in memory is enough, so I need a method to create file storage and mmap storage with compeltion type.

### CODE REVIEW

**Comment by anacrolix** [comment]
Uff, why not make pieceCompletion a parameter? Then you can pass whatever you want.

**Comment by mlmhl** [comment]
Thanks @anacrolix , this is a good idea, I will update the commit and submit it later.

**Comment by mlmhl** [comment]
hi @anacrolix I have make pieceCompletion as a parameter, maybe you want to reveiw this.

**Comment by anacrolix** [comment]
Great work.

**Pull request merged**
