### PR TITLE
Adds PieceCompletion Implementation for Postgresql. 

### PR DESCRIPTION
**Pull request by gitpubber**
It is tested in my computer and
works fine.

@anacrolix  , this is bugless and works fine.

### CODE REVIEW

**Comment by anacrolix** [comment]
It's a fine implementation, but I don't want to add it to the core without tests. Perhaps it belongs in a contrib repo of some kind.

**Comment by gitpubber** [comment]
Alright, no problem for me if you don't want to include this in main repo but please merge DoOnClose() function to let me close this psql connection on Client Close

**Comment by anacrolix** [comment]
Can you not close the Client, and then your psql connection outside the library?

**Comment by gitpubber** [comment]
> Can you not close the Client, and then your psql connection outside the library?

https://github.com/anacrolix/torrent/blob/b8e1c9539907b177a7dac66c95304c0dbe91475f/client.go#L214

i wanted to just do this. ofcourse,it can be closed outside. but, suppose,i use NewBoltdbcompletion function, i am not able to close it

**Comment by anacrolix** [comment]
You could mention your Postgres piece completion implementation in Discussions for others.

**Comment by gitpubber** [comment]
> You could mention your Postgres piece completion implementation in Discussions for others.

Yes, I will. 

Can you please look at why Sqlite3 PieceImplementation panics. Thanks in advance

**Pull request closed without merging**
