### PR TITLE
fix: clear UPNP port mappings when client close

### PR DESCRIPTION
**Pull request by monkeyWie**
related: https://github.com/anacrolix/upnp/pull/2

### CODE REVIEW

**Comment by anacrolix** [comment]
This looks good. I'll review more carefully tomorrow.

**Comment by anacrolix** [comment]
Thanks!

**Comment by tsynik** [comment]
Backported this code to old codebase https://github.com/tsynik/torrent/commit/01ff04216d249b3df31e07f0f8c84675421b819c and have strange bug on DeletePortMapping: it deletes TCP port twice and don't do it for UDP. Also printed cl.upnpMappings in Close() to check it have both TCP and UDP and it is true.
```
2024/05/25 15:08:20 UTC0 disconect
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/torrent client.go:359]
  Close() upnpMapping: &{334eb979-55da-4216-9a49-d2f56bb4ad45 {urn:schemas-upnp-org:device:WANDevice:1 WANDevice [{urn:schemas-upnp-org:device:WANConnectionDevice:1 WANConnectionDevice [] [{urn:upnp-org:serviceId:WANIPConn1 urn:schemas-upnp-org:service:WANIPConnection:1 /ctl/IPConn}]}] [{urn:upnp-org:serviceId:WANCommonIFC1 urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1 /ctl/CmnIfCfg}]} urn:upnp-org:serviceId:WANIPConn1 http://192.168.77.7:50503/ctl/IPConn urn:schemas-upnp-org:service:WANIPConnection:1 192.168.77.11 {{{true [] [0xc0001f0e00 upnp-discover] {0} {1} [] [{0xc00012c010 0x13c4e20}]}}}} UDP 56123
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/torrent client.go:359]
  Close() upnpMapping: &{334eb979-55da-4216-9a49-d2f56bb4ad45 {urn:schemas-upnp-org:device:WANDevice:1 WANDevice [{urn:schemas-upnp-org:device:WANConnectionDevice:1 WANConnectionDevice [] [{urn:upnp-org:serviceId:WANIPConn1 urn:schemas-upnp-org:service:WANIPConnection:1 /ctl/IPConn}]}] [{urn:upnp-org:serviceId:WANCommonIFC1 urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1 /ctl/CmnIfCfg}]} urn:upnp-org:serviceId:WANIPConn1 http://192.168.77.7:50503/ctl/IPConn urn:schemas-upnp-org:service:WANIPConnection:1 192.168.77.11 {{{true [] [0xc0001f0e00 upnp-discover] {0} {1} [] [{0xc00012c010 0x13c4e20}]}}}} TCP 56123
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/upnp upnp.go:466]
  SOAP Request URL: http://192.168.77.7:50503/ctl/IPConn
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/upnp upnp.go:466]
  SOAP Request URL: http://192.168.77.7:50503/ctl/IPConn
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/upnp upnp.go:467]
  SOAP Action:
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/upnp upnp.go:467]
  SOAP Action:
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/upnp upnp.go:468]
  SOAP Request:

<?xml version="1.0" ?>
	<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body><u:DeletePortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
	<NewRemoteHost></NewRemoteHost>
	<NewExternalPort>56123</NewExternalPort>
	<NewProtocol>TCP</NewProtocol>
	</u:DeletePortMapping></s:Body>
	</s:Envelope>
[2024-05-25 18:08:20 +0300 DBG github.com/anacrolix/upnp upnp.go:468]
  SOAP Request:

<?xml version="1.0" ?>
	<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body><u:DeletePortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
	<NewRemoteHost></NewRemoteHost>
	<NewExternalPort>56123</NewExternalPort>
	<NewProtocol>TCP</NewProtocol>
	</u:DeletePortMapping></s:Body>
	</s:Envelope>
2024/05/25 15:08:20 UTC0 connect
```

**Comment by monkeyWie** [comment]
@tsynik Thanks for your feedback, it is absolute my mistake, I'll fix it ASAP!

**Comment by anacrolix** [comment]
Thanks to you both!

**Pull request merged**
