### PR TITLE
adding custom net.Conn struct to return proper RemoteAddr for proxied…

### PR DESCRIPTION
**Pull request by elgatito**
… connections.

Have added custom struct to return proper RemoteAddr for proxied connections.
Built-in connections do not return it properly.

Needs some overview. I have also modified dialers composition.

PS: While debugging this, I have noticed we try each address with 4 protocols, for example, "93.85.33.185:62673" is sent to `socket.dial()` for all networks (tcp4, tcp6, udp4, udp6). Should we really fire those connections is address is not an IPv6?

### CODE REVIEW

**Comment by anacrolix** [comment]
Can you describe the issues caused by having the wrong remote address? What would you think of having remoteAddr on connection instead (instead of adding the netConn wrapper), and using that everywhere that wants to do checks? I am guessing the main issue with RemoteAddr as it is, is that connections to the same proxy are handled like connections to the same peer?

I believe it's possible to connect to IPv4 addresses over IPv6, so I'm leaning toward yes, unless there's a measurable performance impact.

**Comment by anacrolix** [comment]
How do incoming connections work when you have proxies? Do you just not receive any?

**Comment by anacrolix** [comment]
I was thinking something like https://github.com/anacrolix/torrent/pull/288. Let me know what you think, and if it works for you.

**Comment by elgatito** [comment]
> Can you describe the issues caused by having the wrong remote address? 

First of all, all connections are treated like the same peer, stats show like "10 connections out of 1 peers", because remoteaddr point to the same peer.
Not sure it was caused by that, but suddenly all connections were closed.

> What would you think of having remoteAddr on connection instead (instead of adding the netConn wrapper), and using that everywhere that wants to do checks? I am guessing the main issue with RemoteAddr as it is, is that connections to the same proxy are handled like connections to the same peer?

Probably. Not sure, but it can be.

> I believe it's possible to connect to IPv4 addresses over IPv6, so I'm leaning toward yes, unless there's a measurable performance impact.

https://en.wikipedia.org/wiki/6to4
Probably. My concern is about making 4 outgoing connections for every peer. Do they come over rate limiting? I mean, if we want to make 50 peers, do we try 50*4 or we try 50 outgoing connections?


> How do incoming connections work when you have proxies? Do you just not receive any?

They don't come from proxy, they are only proxying connections from my side. Incoming connections are working when using VPN. That is fine.

**Comment by anacrolix** [comment]
> Probably. My concern is about making 4 outgoing connections for every peer. Do they come over rate limiting? I mean, if we want to make 50 peers, do we try 50*4 or we try 50 outgoing connections?
It's 50*4, for now.
> 
> > How do incoming connections work when you have proxies? Do you just not receive any?
> 
> They don't come from proxy, they are only proxying connections from my side. Incoming connections are working when using VPN. That is fine.
Okay thanks.

**Pull request closed without merging**
