### PR TITLE
Add per-torrent ability to disable uploading

### PR DESCRIPTION
**Pull request by max-b**
Provides for ability to mark specific torrents as "don't upload".

### CODE REVIEW

**Comment by anacrolix** [comment]
That should do it. It might be desirable to add an option when the torrent is added too. Probably to https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Client.AddTorrentSpec.

**Comment by anacrolix** [comment]
There's also some logging calls that might want to be removed.

**Comment by max-b** [comment]
Thanks! I can make another quick PR for the logs and for the `AddTorrentSpec`

**Comment by anacrolix** [comment]
Sounds excellent!

**Pull request merged**
