### PR TITLE
Optimize getIp() and make inlineable

### PR DESCRIPTION
**Pull request by YenForYang**
A few changes that make things clearer and reduce chances of hitting another Go gotcha. Go also is pretty bad at moving loop-invariant code out of loops, so this should help thing in that front as well.

### CODE REVIEW

**Comment by anacrolix** [comment]
Please use go fmt.

**Comment by YenForYang** [comment]
Usually my formatting lines up exactly with go fmt, but when it comes to `switch` I get carried away with making the lines line up lol. I fixed it.

**Comment by anacrolix** [comment]
I think Go's early return convention still has legs here. This function accumulates indentation in the new form.

**Comment by YenForYang** [comment]
I could move the variable declaration out of the switch and remove the default case to reduce indentation, but that would increase variable scope. I personally would rather reduce scope than worry about indentation. But I'm willing to change it if you have any ideas.

**Pull request closed without merging**
