### PR TITLE
Add err != nil check to avoid meaningless log

### PR DESCRIPTION
**Pull request by half-dead**

### CODE REVIEW

**Comment by anacrolix** [comment]
If you look earlier, you'll see a check that the correct number of bytes were hashed. If the number is not correct, it's actually an error if err == nil. Are you seeing it log an error with err == nil?

**Comment by half-dead** [comment]
Here is what I did:
Start a private tracker using BitTornado(a BitTorrent client wrote with python)
Start a seeder with: torrent --seed=true test.torrent
Start a peer on another host with: torrent test.torrent

The downloading went good, but I'm seeing a lot of logs like these:

```
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
2016/03/26 02:08:45 torrent.go:670: unexpected error hashing piece with file.data: %!s(<nil>)
consul.log [=================================================================>--]  97% downloading (697 MB/698 MB)
2016/03/26 02:08:55 main.go:144: downloaded ALL the torrents
[root@HV15090349 dist]#
```

Not sure what's the problem here, I'm new to this project, just started yesterday.

If this is unreproducible in your environment, I'm happy to run tests in mine, just tell me how.

Here is my working go version:
```
go version go1.5.3 darwin/amd64
```

And the compile command(gox is an open source go cross compile tool):
```
gox -osarch="linux/amd64" -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/torrent/
```

**Comment by anacrolix** [comment]
Thanks for the info, it should be enough to go on.

**Comment by anacrolix** [comment]
Looks like it's file.data.ReadAt returning io.EOF and then io.Copy throwing away that error.

**Comment by anacrolix** [comment]
4986c61138f0444ed07c15e7dba3902ccb69116e should fix the issue.

**Pull request closed without merging**
